SUPER_CONFIG_PATH: train_base.yaml

OUTPUTS_DIR: /train_8ch_stage1

SAMPLE_LENGTHS: [1]       # Only sampling one frame for detection

DETR_NUM_TRAIN_FRAMES: 100                                # >> BS

# # Train Setting:
TRAIN_STAGE: only_detr
EPOCHS: 60
LR: 2.0e-4
LR_WARMUP_EPOCHS: 0
SCHEDULER_MILESTONES: [45]
SCHEDULER_GAMMA: 0.1
BATCH_SIZE: 4
ACCUMULATE_STEPS: 1

#首层10倍(相对于backbone)
LR_DICTIONARY_NAMES: [backbone.0.body.conv1]
LR_DICTIONARY_SCALE: 1

DETR_PRETRAIN: /weights/to/r50_deformable_detr_plus_iterative_bbox_refinement-checkpoint_convhsi.pth

NUM_WORKERS: 2

# # Eval:
INFERENCE_ONLY_DETR: True
SAVE_CHECKPOINT_PER_EPOCH: 5

